"""add email unique Constraint

Revision ID: 335aa3e845a0
Revises: 6bb41fa9616c
Create Date: 2024-05-03 21:02:15.748798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335aa3e845a0'
down_revision = '6bb41fa9616c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts_user', schema=None) as batch_op:
        batch_op.create_unique_constraint("email_unique", ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts_user', schema=None) as batch_op:
        batch_op.drop_constraint("email_unique", type_='unique')

    # ### end Alembic commands ###
