"""add email verification field

Revision ID: 6bb41fa9616c
Revises: c8a362cc95af
Create Date: 2024-05-03 21:00:10.391761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb41fa9616c'
down_revision = 'c8a362cc95af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts_user', schema=None) as batch_op:
        batch_op.create_unique_constraint("username_unique", ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts_user', schema=None) as batch_op:
        batch_op.drop_constraint("username_unique", type_='unique')

    # ### end Alembic commands ###
