"""delete unused fields

Revision ID: 8d08032ea291
Revises: ee2f7a0af3df
Create Date: 2024-05-18 00:55:16.045181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d08032ea291'
down_revision = 'ee2f7a0af3df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('img', sa.String(length=256), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('accepted_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('task')
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('q_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'question', ['q_id'], ['id'])
        batch_op.drop_column('q_id')

    with op.batch_alter_table('answer_like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('q_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'question', ['q_id'], ['id'])
        batch_op.drop_column('q_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('DOB', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shcool', sa.String(length=64), nullable=True))
        batch_op.drop_column('nickname')
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('nickname', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('shcool')
        batch_op.drop_column('DOB')

    with op.batch_alter_table('answer_like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('q_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'task', ['t_id'], ['id'])
        batch_op.drop_column('q_id')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('t_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'task', ['t_id'], ['id'])
        batch_op.drop_column('q_id')

    op.create_table('task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('img', sa.VARCHAR(length=256), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('view_count', sa.INTEGER(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=64), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('date_to_finish', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('accepted_user_id', sa.INTEGER(), nullable=True),
    sa.Column('location', sa.VARCHAR(length=128), nullable=True),
    sa.ForeignKeyConstraint(['accepted_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('question')
    # ### end Alembic commands ###
