"""change name

Revision ID: a718160e17cd
Revises: f572485af969
Create Date: 2024-05-07 18:42:59.013274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a718160e17cd'
down_revision = 'f572485af969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_to_finish', sa.DateTime(), nullable=True))
        batch_op.drop_column('date_to_answer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_to_answer', sa.DATETIME(), nullable=True))
        batch_op.drop_column('date_to_finish')

    # ### end Alembic commands ###
