"""add category field

Revision ID: ae4875e26b0b
Revises: 597d75cbdb96
Create Date: 2024-05-07 17:48:11.204229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae4875e26b0b'
down_revision = '597d75cbdb96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa_task', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
