"""add location

Revision ID: f256b8c87c58
Revises: ae2bf3b3260f
Create Date: 2024-05-08 17:55:33.625738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f256b8c87c58'
down_revision = 'ae2bf3b3260f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=128), nullable=True))
        batch_op.drop_column('reorder')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reorder', sa.INTEGER(), nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###
